services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: language_companion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d language_companion"]
      interval: 5s
      timeout: 5s
      retries: 5

  # You can add MongoDB and Redis later
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
  # mongo_data: